-- CareerZim Postgres schema (Supabase). Enable RLS; users access own rows.
create table if not exists profiles (id uuid primary key references auth.users, full_name text, title text, email text, phone text, location text default 'Harare', country text default 'Zimbabwe', linkedin text, github text, portfolio text, summary text, skills text[] default '{}', soft_skills text[] default '{}', desired_titles text[] default '{}', industries text[] default '{}', preferred_locations text[] default '{Harare}', work_mode text default 'Hybrid', salary_expectation text, employment_types text[] default '{}', actively_looking boolean default true, career_goal text, created_at timestamptz default now());
create table if not exists experience (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users, title text, company text, location text, start_date text, end_date text, current boolean default false, bullets text[] default '{}');
create table if not exists education (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users, school text, qualification text, field text, start_year text, end_year text);
create table if not exists projects (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users, name text, description text, tech text[] default '{}', link text);
create table if not exists certifications (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users, name text, issuer text, year text);
create table if not exists cvs (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users, name text, template text default 'ATS-friendly', profile jsonb, tailored_for_job uuid, changes text[] default '{}', score jsonb, created_at timestamptz default now());
create table if not exists companies (id uuid primary key default gen_random_uuid(), name text unique, industry text, location text, website text, overview text);
create table if not exists job_sources (id uuid primary key default gen_random_uuid(), name text, url text, kind text, active boolean default true, last_sync timestamptz, jobs_collected int default 0, error_log text);
create table if not exists jobs (id uuid primary key default gen_random_uuid(), title text, company text, location text, country text default 'Zimbabwe', category text, type text, mode text, salary text, posted date, deadline date, description text, requirements text[] default '{}', preferred text[] default '{}', apply_url text, apply_email text, source text, created_at timestamptz default now());
create table if not exists applications (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users, job_id uuid references jobs, job_title text, company text, status text default 'Saved', date_applied date default current_date, deadline date, cv_id uuid, cover_letter text, method text, contact text, notes text, interview_date timestamptz, follow_up_date date);
create table if not exists cover_letters (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users, job_id uuid, company text, job_title text, tone text, body text, created_at timestamptz default now());
create table if not exists job_alerts (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users, query text, location text, category text, email boolean default true, in_app boolean default true, created_at timestamptz default now());
create table if not exists notifications (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users, title text, body text, kind text, read boolean default false, created_at timestamptz default now());
-- RLS: alter table profiles enable row level security; create policy "own" on profiles for all using (auth.uid()=id);
-- Repeat own-row policies for user tables; jobs/companies/sources readable by all authenticated.
