import type { Job } from '@/lib/types';
import { EXTRA_JOBS } from './jobs-extra';
const d = (n: number) => { const t = new Date(); t.setDate(t.getDate() + n); return t.toISOString().slice(0, 10); };
const BASE: Job[] = [
  { id:'j1', title:'Junior Software Developer', company:'ABC Technologies', location:'Harare', country:'Zimbabwe', category:'Software Development', type:'Full-time', mode:'Hybrid', salary:'USD 800–1,200 / month', posted:d(-8), deadline:d(22), description:'Junior Software Developer with React, TypeScript and REST API experience. Build web apps, write clean code, use Git and SQL databases.', requirements:['React','TypeScript','JavaScript','REST APIs','Git','SQL'], preferred:['Next.js','Node.js'], applyEmail:'careers@abctech.co.zw', source:'Company career page', featured:true },
  { id:'j2', title:'Graduate Trainee — Software Engineering', company:'Econet Wireless', location:'Harare', country:'Zimbabwe', category:'Graduate Trainee', type:'Graduate Trainee', mode:'Onsite', salary:'Competitive', posted:d(-6), deadline:d(17), description:'12-month graduate programme for Computer Science graduates. Rotations in software and product.', requirements:['Computer Science degree','Java or Python','SQL','Communication'], preferred:['Internship experience'], applyUrl:'https://www.econet.co.zw/careers', source:'Employer website', featured:true },
  { id:'j3', title:'IT Support Technician', company:'CBZ Bank', location:'Harare', country:'Zimbabwe', category:'IT', type:'Full-time', mode:'Onsite', salary:'Competitive', posted:d(-10), deadline:d(12), description:'First-line IT support, Active Directory, networking, branch user support.', requirements:['IT Support','Windows','Networking','Active Directory'], preferred:['ITIL'], applyEmail:'jobs@cbz.co.zw', source:'Job board' },
  { id:'j7', title:'Frontend Developer (React)', company:'Paynow Zimbabwe', location:'Harare', country:'Zimbabwe', category:'Software Development', type:'Full-time', mode:'Hybrid', salary:'USD 1,500–2,500', posted:d(-7), deadline:d(20), description:'Build fintech dashboards with React, Next.js, Tailwind. REST APIs, tests, performance.', requirements:['React','Next.js','Tailwind CSS','TypeScript','REST APIs','Git'], preferred:['Fintech experience'], applyUrl:'https://www.paynow.co.zw/careers', source:'Employer website', featured:true },
  { id:'j6', title:'Digital Marketing Intern', company:'ZimTech Media', location:'Remote', country:'Zimbabwe', category:'Internship', type:'Internship', mode:'Remote', salary:'Stipend USD 150', posted:d(-4), deadline:d(27), description:'Remote internship: social media, SEO, content creation.', requirements:['Social media','Writing','Canva'], preferred:['SEO'], applyEmail:'hello@zimtechmedia.co.zw', source:'Job board', featured:true },
  { id:'j11', title:'Earn USD 10,000 guaranteed', company:'Quick Cash Ltd (unverified)', location:'Harare', country:'Zimbabwe', category:'Finance', type:'Full-time', mode:'Remote', salary:'USD 10,000 guaranteed!!!', posted:d(-3), deadline:d(3), description:'GUARANTEED income! Send $50 registration fee via EcoCash to unlock job. No interview, WhatsApp only!!!', requirements:['WhatsApp'], preferred:[], applyEmail:'quickcash999@gmail.com', source:'Unknown' },
];
export const JOBS: Job[] = [...BASE, ...EXTRA_JOBS];
