import type { Job } from '@/lib/types';
const d = (n: number) => { const t = new Date(); t.setDate(t.getDate() + n); return t.toISOString().slice(0, 10); };
export const EXTRA_JOBS: Job[] = [
  { id:'j14', title:'Customer Service Agent', company:'NetOne', location:'Masvingo', country:'Zimbabwe', category:'Customer Service', type:'Full-time', mode:'Onsite', salary:'Competitive', posted:d(-4), deadline:d(23), description:'Call centre, OneMoney queries, CRM.', requirements:['Communication','Computer literacy'], preferred:['Call centre experience'], applyUrl:'https://www.netone.co.zw/careers', source:'Employer website' },
  { id:'j15', title:'Junior QA Tester', company:'TechnoServe ZW', location:'Remote', country:'Zimbabwe', category:'Software Development', type:'Contract', mode:'Remote', salary:'USD 600–900', posted:d(-3), deadline:d(28), description:'Manual and automated testing, Playwright, bug reports.', requirements:['Testing','Playwright or Selenium','Git'], preferred:['TypeScript'], applyEmail:'qa@technoserve.co.zw', source:'Job board' },
  { id:'j16', title:'UI/UX Designer', company:'Fresh Ideas Agency', location:'Harare', country:'Zimbabwe', category:'Design', type:'Contract', mode:'Hybrid', salary:'USD 700–1,100', posted:d(-6), deadline:d(16), description:'Figma wireframes, prototypes, design systems.', requirements:['Figma','UI design','Portfolio'], preferred:['User research'], applyEmail:'jobs@freshideas.co.zw', source:'Job board' },
  { id:'j17', title:'Logistics Driver', company:'DHL Zimbabwe', location:'Harare', country:'Zimbabwe', category:'Logistics', type:'Full-time', mode:'Onsite', salary:'Competitive', posted:d(-7), deadline:d(14), description:'Deliveries across Harare, defensive driving.', requirements:['Class 4 licence','Defensive driving'], preferred:['Experience'], applyUrl:'https://www.dhl.co.zw', source:'Employer website' },
  { id:'j18', title:'Graduate Trainee — Banking', company:'Stanbic Bank', location:'Harare', country:'Zimbabwe', category:'Graduate Trainee', type:'Graduate Trainee', mode:'Onsite', salary:'Competitive', posted:d(-5), deadline:d(19), description:'18-month banking rotations: retail, corporate, risk.', requirements:['Banking or Finance degree','Excel','Communication'], preferred:['Attachment experience'], applyUrl:'https://www.stanbicbank.co.zw', source:'Employer website' },
  { id:'j19', title:'Content Writer (Contract)', company:'NewsDay Digital', location:'Chitungwiza', country:'Zimbabwe', category:'Media', type:'Contract', mode:'Hybrid', salary:'USD 400–700', posted:d(-2), deadline:d(29), description:'Daily Zimbabwe news, SEO headlines.', requirements:['Writing','SEO','WordPress'], preferred:['Portfolio'], applyEmail:'digital@newsday.co.zw', source:'Job board' },
  { id:'j20', title:'Mobile Developer (Flutter)', company:'EcoCash Fintech', location:'Harare', country:'Zimbabwe', category:'Software Development', type:'Full-time', mode:'Hybrid', salary:'USD 1,400–2,200', posted:d(-4), deadline:d(24), description:'Flutter apps, mobile money APIs, testing.', requirements:['Flutter','Dart','REST APIs','Git'], preferred:['Firebase'], applyUrl:'https://www.ecocash.co.zw/careers', source:'Employer website' },
  { id:'j21', title:'Intern — Software (6 months)', company:'ZOL Zimbabwe', location:'Bulawayo', country:'Zimbabwe', category:'Internship', type:'Internship', mode:'Onsite', salary:'Stipend', posted:d(-3), deadline:d(30), description:'Pair with seniors, fix bugs, write docs.', requirements:['JavaScript','Git','Eagerness to learn'], preferred:['React'], applyEmail:'interns@zol.co.zw', source:'Job board' },
  { id:'jx2', title:'Work from home, no interview needed', company:'Global Earners (unverified)', location:'Remote', country:'Zimbabwe', category:'Data Entry', type:'Contract', mode:'Remote', salary:'USD 5,000/week guaranteed', posted:d(-2), deadline:d(10), description:'No interview! Just pay $30 training fee via EcoCash and start earning. Contact WhatsApp only.', requirements:['WhatsApp','Smartphone'], preferred:[], applyEmail:'globalearners7@gmail.com', source:'Unknown' },
  { id:'jx3', title:'Urgent hiring — pay admin fee first', company:'Trust Jobs Agency (unverified)', location:'Bulawayo', country:'Zimbabwe', category:'General', type:'Full-time', mode:'Onsite', salary:'USD 3,000/month, no experience', posted:d(-1), deadline:d(12), description:'Urgent! Send $20 admin fee to process your application. Guaranteed placement, no interview required.', requirements:['WhatsApp'], preferred:[], applyEmail:'trustjobsagency@gmail.com', source:'Unknown' },
];
